storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 10.0.0.43
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
training:
  data:
    batch_size: 128
    dataset: imagenet
  loss: cross_entropy
  lr_scheduler:
    baseline_lr: 0.1
    gamma: 0.1
    lrmilestone: 30 60 90
    type: multistep
  model:
    model_type: resnet50
  optimizer:
    learning_rate: 0.1
    mode: initialization
    momentum: 0.9
    optimizer: SFW
    ord: 2
    rescale: gradient
    value: 30
    weight_decay: 0.0001
training_identifier:
  id: '30'
