storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 10.0.0.22
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
training:
  data:
    batch_size: 128
    dataset: mnist
  loss: cross_entropy
  lr_scheduler:
    baseline_lr: 0.1
    gamma: 0.1
    lrmilestone: 100 200 300
    type: multistep
  model:
    model_type: net
  optimizer:
    learning_rate: 0.1
    mode: initialization
    momentum: 0.9
    optimizer: SGD
    ord: 2
    rescale: gradient
    value: 30
    weight_decay: 0.0001
  round:
    gamma: 0.95
    mu: 0.001
    type: fedavg
training_identifier:
  id: '57'
